librevenge: add -lboost_system to pkgconfig
In current masters of out meta-verse this is required to fix dependent
libraries fail during link:

| /home/superandy/tmp/oe-core-glibc/sysroots/x86_64-linux/usr/lib/librevenge-0.0.so: undefined reference to `boost::system::system_category()'
| /home/superandy/tmp/oe-core-glibc/sysroots/x86_64-linux/usr/lib/librevenge-0.0.so: undefined reference to `boost::system::generic_category()'

Signed-off-by: Andreas Müller <schnitzeltony@googlemail.com>